# Copyright 2020 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

from flask import Flask

from securescaffold import factory


def test_create_app_returns_an_app():
    app = factory.create_app("test")

    assert isinstance(app, Flask)


def test_create_app_does_not_add_report_to_headers():
    app = factory.create_app("test")
    client = app.test_client()

    resp = client.get("/")

    assert "Report-To" not in resp.headers


def test_create_app_adds_csp_headers():
    app = factory.create_app("test")
    client = app.test_client()

    resp = client.get("/")

    expected = (
        "font-src 'self' themes.googleusercontent.com *.gstatic.com; frame-src"
        " 'self' www.google.com www.youtube.com; script-src 'self'"
        " ajax.googleapis.com *.googleanalytics.com *.google-analytics.com;"
        " style-src 'self' ajax.googleapis.com fonts.googleapis.com"
        " *.gstatic.com; object-src 'none'; default-src 'self' *.gstatic.com"
    )
    assert resp.headers["Content-Security-Policy"] == expected


def test_create_app_adds_other_security_headers():
    """Useful security headers generated by flask-talisman."""
    app = factory.create_app("test")
    client = app.test_client()
    response = client.get("/")

    assert response.headers["Referrer-Policy"] == "strict-origin-when-cross-origin"
    assert response.headers["X-Content-Type-Options"] == "nosniff"
    assert response.headers["X-Frame-Options"] == "SAMEORIGIN"
    assert "X-Xss-Protection" not in response.headers


def test_extra_flask_args():
    app = factory.create_app("test", static_url_path="/foo")
    assert app.static_url_path == "/foo"


def test_given_flask_name():
    app = factory.create_app("foo")
    assert app.name == "foo"


def test_get_talisman_config():
    """Check what keyword arguments we will feed to flask-talisman."""
    config = {
        "CSP_POLICY": {"foo": "bar"},
        "CSP_POLICY_NONCE_IN": ["script-src", "style-src"],
        "CSP_POLICY_REPORT_ONLY": True,
        "CSP_POLICY_REPORT_URI": "/baz",
    }
    result = factory.get_talisman_config(config)

    expected = {
        "content_security_policy": {"foo": "bar"},
        "content_security_policy_nonce_in": ["script-src", "style-src"],
        "content_security_policy_report_only": True,
        "content_security_policy_report_uri": "/baz",
    }

    assert result == expected
